name: docker image

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOC_USERNAME }} -p ${{ secrets.DOC_PASSWORD }}

      - name: Build Docker image
        run: docker build -t 365docker/training:late -f Dockerfile .

      - name: Tag Docker image
        run: docker tag 365docker/training:late 365docker/training:late

      - name: Push Docker image to Docker Hub
        run: docker push 365docker/training:late

      - name: pull docker from the docker hub
        run:  docker pull 365docker/training:late 

      - name: run the docker image in ec2
        run:  |
           echo "${{ secrets.SSH_KEY }}" | base64 --decode > docker.pem
           ssh -o StrictHostKeyChecking=no -i docker.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }} 'sudo docker run -d -p 5000:5000 --name tom_container 365docker/training:late'

