name: docker image

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOC_USERNAME }} -p ${{ secrets.DOC_PASSWORD }}

      - name: Build Docker image
        run: docker build -t 365docker/training:late -f Dockerfile .

      - name: Tag Docker image
        run: docker tag 365docker/training:late 365docker/training:late

      - name: Push Docker image to Docker Hub
        run: docker push 365docker/training:late

      - name: Pull Docker image from Docker Hub
        run: docker pull 365docker/training:late

      - name: SSH into EC2 and run Docker command
        run: |
          docker run -d -p 5000:5000 --name my-container 365docker/training:late
        if: success()
           echo "Succesfully deployed"

