name: flask_app

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      -master

jobs:
  test:
    runs-on: linux
    defaults:
      run:
        working-directory: ./app/
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: test app code
        run: python ./flak_app.py

         -
      - name: Build and push docker image
        uses: docker/login-action@v3
        with:
          image: 365docker/training
          registry: docker.io
          username: ${{ secrets.DOC_USERNAME }}
          password: ${{ secrets.DOC_PASSWORD }}
