name: flask_app

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: linux
    defaults:
      run:
        working-directory: ./app/
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test app code
        run: python ./flak_app.py

  build_and_push_docker:
    runs-on: linux
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: 365docker / training
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOC_USERNAME }}
          password: ${{ secrets.DOC_PASSWORD }}

